FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/vitouchiha/Catalog-Translator /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
